services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  BizUserBundle\DataFixtures\:
    resource: '../../DataFixtures/'
  BizUserBundle\Repository\:
    resource: '../../Repository/'
  BizUserBundle\Service\:
    resource: '../../Service/'

  biz-user.property-accessor:
    class: Symfony\Component\PropertyAccess\PropertyAccessor
    factory: [ 'Symfony\Component\PropertyAccess\PropertyAccess', 'createPropertyAccessor' ]
